//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int employee_id { get; set; }
        public string employeePayrollNumber { get; set; }
        public string employeeForename { get; set; }
        public string employeeSurname { get; set; }
        public System.DateTime employeeDateOfBirth { get; set; }
        public int employeeTelephone { get; set; }
        public int employeeMobile { get; set; }
        public string employeeAddress { get; set; }
        public string employeeAddress2 { get; set; }
        public string employeePostcode { get; set; }
        public string employeeEmail { get; set; }
        public System.DateTime employeeStartDate { get; set; }
        public string Category { get; set; }
    }
}
